### PR TITLE
Ensure resource files are included in jar

### LINKED ISSUE #20: Resources are broken in 0.1.0
Introduced by https://github.com/sifive/api-scala-sifive/pull/19

When creating a jar for a project, resources are treated as directories. #19 switched them to being listed by files (to fix other bugs), so now they are effectively ignored and not included in the  resulting jar.

### PR DESCRIPTION
**Pull request by jackkoenig**
Fixes #20

* List resource directories instead of files
* Include a hash of visible files as environment variable to job to
  compile Scala

### CODE REVIEW

**Comment by jackkoenig** [comment]
@erikdanie can you see if this fixes the issue?

**Comment by jackkoenig** [comment]
Once @erikdanie confirms this works. I'll merge to master and release `v0.1.1`

**Comment by erikdanie** [comment]
Testing now...

**Comment by erikdanie** [comment]
It passes CI on PCS! I will merge that PR now, if you want me to merge this one I can do that as well

**Comment by jackkoenig** [comment]
I actually need to change the comparison operator, I'm not sure how bad the current one is but maybe we should point to the full fix

**Comment by erikdanie** [comment]
Ok give me a ping when that's done and I can incorporate it

**Comment by jackkoenig** [comment]
Done, use cade56fdc52e5be864d34d6bc2031e45cd7c4fdb if you can, the old commit no longer exists.

**Pull request merged**
