### PR TITLE
Use 'preinstall', and remove wit 0.12.x compatibility

### PR DESCRIPTION
**Pull request by mmjconolly**
This removes the compatibility mode for old wit versions that fetch scala dependencies.
The `preinstall` topic can now download the scala dependencies too.
It seems to work out that if someone needs the scala deps without having prefetched, it will fetch

* Install scala dependencies: 
    * `wake -x 'fetchScala Unit'`
* Install all dependencies, including scala deps:
    * `wake -x 'preinstall Unit'`

### CODE REVIEW

**Comment by mmjconolly** [comment]
Looks like this need some test case fixups

**Comment by jackkoenig** [comment]
I admit I don't like that `preinstall` requires depending on `api-languages-sifive` and I generally think that languages should be independent. Then again, as implemented, this repo does depend on `python` so barring breaking that dependency, it is technically more accurate.

**Comment by mmjconolly** [comment]
I feel like I've waded a little too far past my understanding of how scala dependencies work,
@jackkoenig am I generally going in the right direction or am I way off?

**Comment by jackkoenig** [comment]
I don't understand how your changes are causing this issue, but just to explain Scala dependencies really fast:
```
Exception: Must specify scalaVersion for IvyDependency org.scalamacros:::paradise:2.1.0!
```
Fortunately I already wrote this doc so I can just paste it here 🙂  (From https://github.com/sifive/api-scala-sifive#dependencies):

"
Standard Java dependencies are of the form `<groupID>:<artifactID>:<revision>`.
Because Scala does not maintain binary compatibility between major versions,
Scala dependencies are specified with two colons after `groupID`: `<groupID>::<artifactID>:<revision>`.
Such dependencies are automatically expanded to `<groupID>:<artifactID>_<scala major version>:<revision>`.

For example, since `scalaVersion` is `"2.12.8"` in this project,
`"ch.epfl.scala::bloop-frontend:1.2.5"` is expanded to `"ch.epfl.scala:bloop-frontend_2.12:1.2.5"`.
This allows us to bump the Scala version without having to update every single Scala dependency.

For Scala dependencies that break compatibility between Scala _minor_ versions, one can use three colons.
For example, `"my.org:::cool-project:1.0.0"` would expand to `"my.org:cool-project_2.12.8:1.0.0"`.
"

**Pull request closed without merging**
